---
# Инвентарь для локальной установки (ansible запускается на самой машине)
all:
  children:
    workstation:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
