---
- name: Converge
  hosts: all
  become: true
  vars:
    firewall_default_incoming: "deny"
    firewall_default_outgoing: "allow"
    firewall_rules:
      - port: "22"
        proto: tcp
        rule: allow
        comment: "SSH"
      - port: "80"
        proto: tcp
        rule: allow
        comment: "HTTP test"
  roles:
    - role: firewall
